#!/usr/bin/env python3
"""Optional public-metadata search for candidate prior work.

This script can search either:
1. a user-supplied query, or
2. short query strings generated locally from a review packet/query plan.

It does not upload the full manuscript text. When --from-packet is used, it first
builds a local query plan from title/abstract/keywords and then sends only those
short query strings to public metadata APIs.
"""
from __future__ import annotations

import argparse
import json
import os
import urllib.parse
import urllib.request
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reviewer_core.io_utils import write_json
from reviewer_core.retrieval import build_query_plan


def get_json(url: str, timeout: int = 30) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "pre-submission-ai-reviewer/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def search_crossref(query: str, rows: int) -> list[dict]:
    url = "https://api.crossref.org/works?" + urllib.parse.urlencode({"query.title": query, "rows": rows})
    data = get_json(url)
    items = data.get("message", {}).get("items", [])
    results = []
    for item in items:
        title = " ".join(item.get("title") or [])
        year = ""
        parts = item.get("published-print", item.get("published-online", {})).get("date-parts", [])
        if parts and parts[0]:
            year = str(parts[0][0])
        results.append({
            "id": item.get("DOI", title[:80]),
            "title": title,
            "year": year,
            "venue": " ".join(item.get("container-title") or []),
            "doi": item.get("DOI", ""),
            "url": item.get("URL", ""),
            "source": "crossref",
            "matched_query": query,
            "relationship_to_current_paper": "requires author assessment",
        })
    return results


def search_openalex(query: str, rows: int) -> list[dict]:
    url = "https://api.openalex.org/works?" + urllib.parse.urlencode({"search": query, "per-page": rows})
    data = get_json(url)
    results = []
    for item in data.get("results", []):
        primary_location = item.get("primary_location") or {}
        source = primary_location.get("source") or {}
        results.append({
            "id": item.get("id", ""),
            "title": item.get("title", ""),
            "year": str(item.get("publication_year", "")),
            "venue": source.get("display_name", "") if isinstance(source, dict) else "",
            "doi": item.get("doi", ""),
            "url": item.get("id", ""),
            "source": "openalex",
            "matched_query": query,
            "relationship_to_current_paper": "requires author assessment",
        })
    return results


def _dedupe(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for e in entries:
        key = (str(e.get("doi") or e.get("id") or e.get("title") or "").strip().lower())
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(e)
    return out


def _load_queries(args: argparse.Namespace) -> tuple[list[str], dict[str, Any] | None]:
    if args.query_plan:
        plan = json.loads(Path(args.query_plan).read_text(encoding="utf-8"))
    elif args.from_packet:
        plan = build_query_plan(Path(args.from_packet), out_path=args.write_query_plan, extra_terms=args.extra_term, max_queries=args.max_queries)
    else:
        plan = None

    if plan is not None:
        queries = [q.get("query", "") if isinstance(q, dict) else str(q) for q in plan.get("queries", [])]
        queries = [q for q in queries if q.strip()]
        if args.query:
            queries.insert(0, args.query)
        return queries[: args.max_queries], plan
    if not args.query:
        raise SystemExit("Provide a positional query, --query-plan, or --from-packet.")
    return [args.query], None


def main() -> None:
    ap = argparse.ArgumentParser(description="Search public metadata endpoints for candidate prior work.")
    ap.add_argument("query", nargs="?", help="Manual search query. Optional when --from-packet or --query-plan is used.")
    ap.add_argument("--from-packet", type=Path, default=None, help="Generate short search queries from a local review packet, then search them.")
    ap.add_argument("--query-plan", type=Path, default=None, help="Use an existing query_plan.json generated by generate_prior_work_queries.py.")
    ap.add_argument("--write-query-plan", type=Path, default=None, help="Where to save the generated query plan when --from-packet is used.")
    ap.add_argument("--extra-term", action="append", default=[], help="Optional extra term for query generation. Can be repeated.")
    ap.add_argument("--max-queries", type=int, default=5, help="Maximum generated queries to send to public metadata APIs.")
    ap.add_argument("--source", choices=["crossref", "openalex", "both"], default="both")
    ap.add_argument("--rows", type=int, default=8, help="Rows per query per source.")
    ap.add_argument("--out", type=Path, default=Path("review_packet/prior_work_candidates.json"))
    args = ap.parse_args()

    queries, plan = _load_queries(args)
    results: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []
    offline = os.environ.get("AI_REVIEWER_OFFLINE") == "1"
    if offline:
        errors.append({"query": "*", "error": "skipped: AI_REVIEWER_OFFLINE=1"})
    else:
        for q in queries:
            try:
                if args.source in {"crossref", "both"}:
                    results.extend(search_crossref(q, args.rows))
                if args.source in {"openalex", "both"}:
                    results.extend(search_openalex(q, args.rows))
            except Exception as exc:
                errors.append({"query": q, "error": str(exc)})
    results = _dedupe(results)
    data = {
        "queries": queries,
        "query_plan": plan,
        "privacy_note": "Only short search queries are sent to public metadata APIs; full manuscript text is not uploaded by this script.",
        "offline": offline,
        "prior_work_entries": results,
        "errors": errors,
    }
    write_json(args.out, data)
    print(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"\nWrote prior-work candidates: {args.out}")


if __name__ == "__main__":
    main()
